version: '3.9'

services:
  db:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=flights
      - MYSQL_USER=flight_bot
      - MYSQL_PASSWORD=secret
      - TZ=UTC
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  web:
    build: .
    depends_on:
      - db
    ports:
      - "13000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=flights
      - DB_USER=flight_bot
      - DB_PASS=secret
    restart: unless-stopped

volumes:
  db_data:
